//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Image.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_img
    {
        public int ProductId { get; set; }
        [Required]
        [Display(Name ="Product Name :")]
        public string Productname { get; set; }
        [Required]
        [Display(Name = "Product Price :")]
        [RegularExpression(@"^[0-9]+(\.[0-9]{1,2})$", ErrorMessage = "Valid Decimal number with maximum 2 decimal places.")]
        public Nullable<decimal> ProductPrice { get; set; }
        [Required]
        [Display(Name = "Product code :")]
        [MaxLength(6)]
        public string Productcode { get; set; }
        
        
        [Display(Name = "Upload Image :")]
        public string Productimage { get; set; }
    }
}
